### ISSUE TITLE
`Server` - `DeFiChain` - Address Generator Endpoint

### ISSUE THREAD

**Issue by thedoublejay** [WavesHQ/bridge#144]
#### What would you like to be added:
Create an endpoint to generate an address per transaction when doing DeFiChain -> ERC20. Should be able to optionally specify network. If not provided, set to mainnet as default.

**Comment by weiyuan95** [comment]
Underlying implementation being tackled in #180

**Comment by weiyuan95** [comment]
Take note that this needs to be protected in some way, if not an attacker can infinitely call this endpoint and cause us to create addresses arbitrarily.

**Comment by weiyuan95** [comment]
Something to take note - when generating addresses, let's start from index 2. Index 1 should not be touched (I'm assuming that index 0 is the parent key).

Few reasons
- The smart contract needs to verify against an address / signed message, and it needs to know the address of the signer when deploying the smart contract. If it's not set at deployment, anyone can just sign their own claims and say that it's valid.
- Ideally we do not deal with the base parent (consortium) key at all to prevent potential attack vectors, so we use the first generated address (index 1)

@Abhishekkochar is looking at potential ways to gracefully handle BIP-39 signature verification, but for now let's go with using derived addresses from (inclusive) index 2 onwards.
