### ISSUE TITLE
`Server` - ERC20 - Connect metamask wallet

### ISSUE THREAD

**Issue by thedoublejay** [WavesHQ/bridge#145]
#### What would you like to be added:
Ability to connect to client via metamask wallet. 
https://wagmi.sh/examples/connect-wallet
https://medium.com/@kaishinaw/connect-metamask-with-ethers-js-fc9c7163fd4d

**Comment by weiyuan95** [comment]
Assigning this to `In Progress` since I believe that Lyka is currently working on this.
