### ISSUE TITLE
Contracts should be upgradable

### ISSUE THREAD

**Issue by Abhishekkochar** [WavesHQ/bridge#159]
#### What would you like to be added:
The bridge contract should be upgradable, in the event that we need to update any of the logic, or if a vulnerability was found in the contract.

This should keep in mind any of the usual caveats, for eg. a contract should only be upgradable by an admin address, etc.

**Comment by Abhishekkochar** [comment]
@weiyuan95, In regards to recent upgrade (V2) we can possibly close this issue.

**Comment by weiyuan95** [comment]
Contracts have already been upgraded, and we've addressed the teething issues that came with it as well.
