### ISSUE TITLE
`Contracts` - Acceptance Criteria for EVM bridge testnet deployment

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#171]
### Blurb:
This issue lists out the criteria regarding the deployment of the bridge contracts to the Goerli testnet. Any necessary TODOs can be spawned into separate issues - this will serve as an over-arching issue of the end goals.

### Acceptance Criteria:
These criteria are roughly written in the order I think things should be done, but feel free to work on them concurrently in whichever order.

#### Documentation
- Provide some simple documentation in a `README.md` regarding how to use/test the contract. Will be helpful for our QAs for testing, and will also help devs for integration.
- [x] #184
- [x] How to get ERC20 tokens to test bridging functionality
- [x] When bridging _from_ DeFiChain, what is the expected signed message
- [x] When bridging _to_ DeFiChain, what is the event that devs need to listen to, and what is the payload of that event
- [ ] Sample metamask transaction of claim transaction
- [ ] General explanation on how the contract works from an EVM perspective

#### Contract Deployment-as-code
- Deployments to any network (mainnet, Goerli, etc) should be run as a Hardhat script (or whatever makes sense) from the `smartcontracts` package.
- [This Hardhat plugin](https://github.com/wighawag/hardhat-deploy/tree/master) which seems to give a good DX is something we can explore (An example of this plugin in use [here](https://github.com/safe-global/safe-contracts/tree/main/src/deploy)). If not we can write a native Hardhat script as per the [official docs](https://hardhat.org/hardhat-runner/docs/guides/deploying).
- This will ensure that our deployments are always consistent and won't be prone to any human error
- [x] Deployment script created

#### Testing
- We should 'execute' all the tests that we have written as scenarios against the actual deployed contract on testnet
- For example, if we have written a test `it('Arbitrary EOA should not be able to add token')`, we should try those steps manually against the testnet deployment as a sanity check.
- This will help us to see what the errors and reverts look like from a user POV, and serves as a sanity check of our implementation

#### Documenting Operational Transactions
- We need to document the steps and flow of what each operation does and how to execute them. These should be documented simply enough that even "dummies" would know how to make such a transaction to the bridge, even if it's their first time making a smart contract transaction.
- [x] Fund ERC20 tokens - to transfer ERC20 tokens from an EOA to the Bridge
- [x] Fund Ether - to transfer ERC20 tokens from an EOA to the Bridge
- [x] Adjust allowance
- [x] Add supported token
- [x] Remove supported token
- [x] Withdraw ether
- [x] Withdraw ERC20
- [x] Change relayer address
- [x] Transaction fee change
- [x] Add operational address
- [x] Modify admin address 
- We also need to set up a [Gnosis Safe on testnet](https://help.gnosis-safe.io/en/articles/4591112-safe-on-goerli-testnet) which will help us to do multi-signature transactions for operational use, and ensure that it works well with the bridge.
- [x] Gnosis Safe set up on Goerli

**Comment by cuongquangnam** [comment]
Regarding operational scripts, my concern is that management of private key via console is quite a dangerous thing to do. My suggestions:
a. Fund ERC20 tokens, ETH, they are simple transaction with metamask, would better use metamask to perform this (cold wallet like ledger allows you to integrate with Metamask)
b. Regarding other administrative activities, I would recommend using Safe multisig app by Gnosis https://gnosis-safe.io/ to perform contract interaction. We did the same for administrative stuff related for liquidity mining. The way it works is one person propose the transaction, other people will review the transaction and approve or reject.
Anyway, I think we should try to deploy the code onto testnet and pay attention to operation later.
