### ISSUE TITLE
Server needs to be able to mint DFC tokens

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#185]
#### What would you like to be added:
Server needs to be able to call a DFC node and mint tokens on behalf of a consortium. This should involve
- [ ] Craft a transaction that will be able to use `minttoken`
https://github.com/DeFiCh/wallet/blob/ef186c5d8efab5ea376385f1035b2ad2ba140730/mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx#L361

#### Why is this needed:
Mint tokens to a user when the `BRIDGE_TO_DEFI_CHAIN` event is emitted from the bridge contract.

#### Blocked by:
- How would DFC know that the transaction is on behalf of a consortium member
  -  If it's by signature, where would the private key for this be? How would the server access it

**Comment by thedoublejay** [comment]
Will be closed to be updated with a new flow
