### ISSUE TITLE
Server needs to be able to listen to emitted events from the EVM

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#186]
#### What would you like to be added:
As per title. We need to listen to the `BRIDGE_TO_DEFI_CHAIN` event coming from the [smart contract](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/contracts/BridgeV1.sol#L122-L134).

#### Why is this needed:
Listen to the event coming from chain so that we can execute follow up code.

**Comment by eli-lim** [comment]
It's critical that the disbursement of funds is fault-tolerant
- https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it

**Comment by weiyuan95** [comment]
Great point, it needs to be resilient.

Proposal:
We can keep track of a few variables, the tip `T` (query-able from chain), last checked block `L` (needs to be stored somewhere), and `X`, which is  `T - necessaryNumberOfConfirmations` (math, with the necessary number of confirmations coming from a config variable). We will then process the events from `L` to `X`, which will be transactions/blocks with more than the necessary number of confirmations.

**Comment by weiyuan95** [comment]
Closing this - we don't need to listen to emitted events from the server, we will just use the logic above to query a particular section of the chain instead.
