### ISSUE TITLE
chore(validation): Ethereum transaction hashes should be validated

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#334]
#### What would you like to be added:
In controllers, when handling transaction hashes from an API call,  we should validate that the transaction hash is valid. We can use https://docs.ethers.org/v5/api/utils/transactions/#utils-parseTransaction and https://docs.nestjs.com/techniques/validation#auto-validation to ensure that the hash (or any other relevant properties) can be parsed correctly.

#### Why is this needed:
Validation - should never trust values from a user

**Comment by greggtan** [comment]
The ethers.utils.parseTransaction method is used to parse a raw RLP-encoded Ethereum transaction and return an object with the properties of the transaction. It is not the appropriate method for validating if an input is in the format of a transaction hash.

I suggest using ethers.utils.isHexString(input) && input.length === 66 && input.slice(0, 2) === '0x';
