### ISSUE TITLE
feat(server): API endpoints for balance checking

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#410]
#### What would you like to be added:
We need to add two endpoints

- [ ] `defichain/balance/{tokenSymbol}`
- [x] `ethereum/balance/{tokenSymbol}`

This will query for the balance of the respective tokens on the respective chain's hot wallet/bridge contract.

#### Why is this needed:
Helps to act as a sanity check for the balance on each chain when executing bridging transactions. Bridging transactions will not be able to execute if the wallet on the respective chain does not have enough funds to carry out the transaction.

**Comment by weiyuan95** [comment]
DFC isn't done

**Comment by thedoublejay** [comment]
It's auto closed on PR merge haha should be partially fixed 
<img width="164" alt="image" src="https://user-images.githubusercontent.com/25013382/220233287-703c2462-7aca-42ca-a1d3-a440b7beb341.png">
