### ISSUE TITLE
Signing a claim with version 2.0 is causing an error on client side claiming process

### ISSUE THREAD

**Issue by lykalabrada** [WavesHQ/bridge#461]
#### What happened:
Signing and claiming of tokens is not working properly. On the server side, we are getting the latest version from the contract which is `version 2.0` and uses that to sign the claim, but then when user tries to claim the tokens, it is failing.

#### What you expected to happen:
User should be able to claim the tokens signed by the server using version 2.0

#### Anything else we need to know?:
When using `version 1.0` to sign the claims, there is no issue claiming the token on the client side.

**Comment by Abhishekkochar** [comment]
@weiyuan95  @cuongquangnam FYI, I'm looking into this rn.

**Comment by weiyuan95** [comment]
Contract upgraded at https://goerli.etherscan.io/tx/0xe765bf0dbcf78764dad56d09b9fb2c32b295b4a016120cc0df2d2cc0601c01c2

@lykalabrada you can try it out! Should not need to hardcode to version 1 anymore.

Thanks @Abhishekkochar for the work!
