### ISSUE TITLE
UX - new address generated without user knowing

### ISSUE THREAD

**Issue by izzycsy** [WavesHQ/bridge#519]
#### What UI/UX improvements would you like to be implemented:
– Inform user on step **2 Transact** that qr code address will re-generated upon selecting `ⓧ`

#### Why is this needed:
**Actual:**
– If user sends funds to qr code generated address, and accidentally selects `ⓧ `instead of `Verify transfer`, user may not notice that by selecting `Review Transaction` again generates a new address

#### Which component/screens does this concern?:
DFC → ETH:
on Review Transaction pop-up modal, step **2 Transact**

#### Anything else we need to know?:
**To reproduce:**
1. User select DFC → ETH > at Amount to transfer, input `0.0001` dBTC > at **Address** field, paste `MetaMask address` > `Review transaction`
2. at **Review transaction** pop-up modal, `note:` qr code address
3. Send `0.0001` dBTC to address, select `ⓧ` > redirects to Quantum with previous inputs
4. at Quantum, user selects `Review transaction` > redirects to **Review transaction** pop-up modal >` note:` a new address is generated, but user might think that tx was being processed and selects Verify transfer

**Comment by mikhail-zlochevskyi** [comment]
Additional use case:

if user will send any amount lower than expected, it will stuck on the temporary wallet at least for 24h.
