### ISSUE TITLE
 Quantum does not recognize to-address (only for ETH)

### ISSUE THREAD

**Issue by izzycsy** [WavesHQ/bridge#522]
#### What happened:
**Actual:**
No matter what EVM address users inputs, Quantum will always send it to the MetaMask-linked address
– This only applies dETH → ETH

#### What you expected to happen:
**Expected:**
No matter what EVM address users inputs, Quantum should recognise and send it to that address

#### How to reproduce it (as minimally and precisely as possible):

> Address A = user's own MetaMask address
> Address B = not user's own MetaMask address

1. User select DFC → ETH > at Amount to transfer, input 0.0001 dETH > at Address field, paste `MetaMask address B` > Review transaction
2. at step 1 Initiate, input `DFC TestNet address` > `Continue` > using MLW, send 0.0001 dETH > `Verify transfer` > `Claim tokens` > redirects to MetaMask extension
3. In MetaMask extension,` note:` address to be sent to should be MetaMask address B

#### Anything else we need to know?:
<img width="2316" alt="230223 Quantum - send to incorrect address1" src="https://user-images.githubusercontent.com/65014479/220849919-74aa4be2-9160-457a-ac8e-22112d21b332.png">
<img width="1204" alt="230223 Quantum - send to incorrect address2" src="https://user-images.githubusercontent.com/65014479/220849949-bd438b93-2098-4290-80d1-16ff1583db6f.png">

**Comment by weiyuan95** [comment]
Should be fixed in #467, @Abhishekkochar is upgrading the contract on testnet.

**Comment by mikhail-zlochevskyi** [comment]
Verified on [commit](https://github.com/WavesHQ/bridge/commit/1d5772dd72f0b4a9b96571cc7758c819571f084f)
