### ISSUE TITLE
Error code 3, user unable to use the same generated address to send remaining balance

### ISSUE THREAD

**Issue by izzycsy** [WavesHQ/bridge#532]
```
Ver: 0.10.0
Network: TestNet
Flow: DFC → EVM
Description: If Error code 3, user unable to use the same generated address to send remaining balance
```

#### What happened:
**Actual:**
at step 3 Validate, if user encounters Error code 3: BalanceNotMatched 
The balance in the wallet's address is not equal to the amount filled in the form.
user has no other option but to select x and restart the tx instead of topping up the remaining amount 

#### What you expected to happen:
**Expected:** 
TBC

#### How to reproduce it (as minimally and precisely as possible):
1. Select Source Network: DeFiChain
2. Input `4` USDT > select `Review transaction`
3. at **step 1 Initiate**, paste `DeFiChain (TestNet) address` in text field > `Continue` 
4. at **step 2 Transact**, use MLW to send `1` USDT > go back to Quantum, select `Verify transfer`
5. at **step 3 Validate**, error: Error code 3: BalanceNotMatched > note: user unable to send remaining 3 USDT

#### Anything else we need to know?:
<img width="720" alt="230223 Quantum - Error Code 3" src="https://user-images.githubusercontent.com/65014479/220928474-dfbfdb9c-4285-4a46-acf3-aee9fbaf6a64.png">

**Comment by pierregee** [comment]
This is covered by this PR https://github.com/WavesHQ/bridge/pull/539
