### ISSUE TITLE
Allowance handling issues - Approval loop

### ISSUE THREAD

**Issue by lykalabrada** [WavesHQ/bridge#568]
#### What happened:
1. Approval loop, user is asked to approve spending limit again and again. Confirmation screen never appears.
> I seem to be in an approval loop. This is specifically for wBTC, I have not tried the other tokens. This also happens even though I have the necessary allowance already (as you can see from the ss)

2. Another issue when manually setting the allowance, Quantum is not able to get the latest allowance right away.
> Looks like there's an issue with how we handle allowances - when i manually reset the allowance of the bridge proxy contract to 0, the app doesn't ask me to approve an allowance tx anymore.

#### What you expected to happen:
1. User should only be asked to approve the spending limit once. Then automatically proceed to bridge confirmation.
2. Quantum should be able to detect change in allowance and act accordingly: 
  a. If allowance is enough, no need to ask user for approval 
  b. If allowance is not enough, user should be asked for approval first

#### How to reproduce it (as minimally and precisely as possible):
> 

> repro steps:
> - Fresh address that hasn't interacted with the bridge before (ie. doesn't have the necessary token approval)
> - Try to bridge 1 wBTC
> - Bridge creates and requests for me to sign the approval tx (it correctly shows no allowance at this point)
> - Sign and send the tx
> - Even after the tx is successful, it retries and asks me to do an approval again, resulting in a tx that i've ss'ed below
> - The workaround is to close the re-try modal, and try to initiate the bridge transaction again. It'll then work as expected without the app requesting you to approve more tokens.

> - Set an allowance for the bridge proxy to a large number
> - Do a bridge tx, it'll work as expected
> - Set the allowance to 0
> - App will not ask you to approve allowance anymore, making the bridge tx revert

#### Anything else we need to know?:
Reported by @weiyuan95 🙏 

![image](https://user-images.githubusercontent.com/17063281/221354330-c5aa65d6-69e4-40ed-828b-c6ac1700e936.png)

**Comment by weiyuan95** [comment]
Loop - fixed 
Re-approval - fixed as well!! 

Great job @lykalabrada 🎊
